[package]
name = "pg_sdl2"
license = "MIT"
version = "0.1.0"
readme = "README.md"
resolver = "2"
description = "A SDL2-superset library for easy game or application development."
authors = ["Arnaud Jungo", "Quentin Jungo <quentin.jungo@gmail.com>"]
categories = ["rendering", "api-bindings", "game-engines", "multimedia", "gui"]
keywords = ["SDL", "gui", "graphics", "superset", "engine"]
# repository = "https://github.com/Rust-SDL2/rust-sdl2"
# documentation = "https://rust-sdl2.github.io/rust-sdl2/sdl2/"

[dependencies]
sdl2 = { version = "0.35.2", features = ["ttf"] }
fontdue-sdl2 = "0.3"
fontdue = "0.7.3"
itertools = "0.10.5"
num = "0.4.0"
macros = { path = "macros", version = "0.1.0" }
pg_sdl = { path = "pg_sdl", version = "0.1.0" }

[[example]]
name = "basic"

[[bin]]
name = "pg_sdl2"
path = "examples/basic.rs"
