name: Give an idea
description: Make a suggestion of any kind about the library.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        You can add a suggestion for a new feature or improvement to the library.
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/github/docs/issues).

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](../../docs/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: What article on docs.github.com is affected?
      description: Include links to articles where you're seeing a problem, screenshots, what browser you're using, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What changes are you suggesting?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information, configuration, or data that might be necessary to reproduce the issue.
    validations:
      required: false